# 환경설정

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
import matplotlib.pyplot as plt

In [4]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

In [5]:
kospi_index = pd.read_excel('https://github.com/SNMHZ/DART_8TH/raw/master/mock_investing/data/kospi_index.xlsx', index_col=0)

In [6]:
kospi_list = pd.read_excel('https://github.com/SNMHZ/DART_8TH/raw/master/mock_investing/data/kospi_list.xlsx', index_col=0)

In [7]:
%%time
pricedata = pd.read_excel('https://github.com/SNMHZ/DART_8TH/raw/master/mock_investing/data/revised_price.xlsx', index_col=0)

CPU times: user 24.5 s, sys: 221 ms, total: 24.7 s
Wall time: 26.3 s


In [8]:
ticker_name = pd.read_excel('https://github.com/SNMHZ/DART_8TH/raw/master/mock_investing/data/ticker_name.xlsx', index_col=0)

In [9]:
pricedata_kospi = pricedata[kospi_list.columns]

# 함수

In [10]:
#########################   베타 획득   #########################
#######input
#ticker -> 목표 종목 코드(string)
#priceData -> 가격 정보 데이터프레임. 시계열
#market -> 시장 지수 데이터프레임. 시계열
#period -> 관측 목표 기간
#end -> 관측 마지막 시점
#show_plot -> 베타 그래프 출력 유무. True시 출력.

#######output
#베타(float)
#################################################################
def getBeta(ticker, priceData, market, period, end=0, show_plot=False):
  price_change = priceData[ticker].pct_change()[1:]
  market_change = market[market.columns[0]].pct_change()[1:]
  
  start = end - period

  price_change_sliced = price_change.iloc[start:end]
  market_change_sliced = market_change.iloc[start:end]

  if show_plot:
    model = LinearRegression(normalize=True)
    model.fit(pd.DataFrame(market_change_sliced),pd.DataFrame(price_change_sliced))

    plt.figure(figsize=(7, 7))
    plt.grid(True)
    plt.scatter(market_change_sliced, price_change_sliced, color='black', alpha=0.5)
    aran = np.arange(min(market_change_sliced) ,max(market_change_sliced) , 0.001)
    plt.plot(aran, model.predict(aran.reshape(-1, 1)), color='blue')
    
    plt.show()

  return (np.cov(price_change_sliced, market_change_sliced)/np.var(market_change_sliced))[0,1]

In [11]:
######################   Bag of Beta 획득   #####################
#######input
#ticker -> 목표 종목 코드(string)
#observation_time -> 관측을 하는 시점(int)
#observation_period -> 관측할 기간(int)
#observation_step -> 관측 step(int)

#######output
#state -> '종목코드_관측시점'. ex) 'A005930_2016-12-08'(string)
#BoB -> 기간 베타 리스트. [230베타, 225베타 220베타, ... , 10~15베타, 5~10베타, 0~5베타](list)
#################################################################
def getBoB(ticker, observation_time, observation_period=230, observation_step=5):
  try:
    BoB = []
    current_period = observation_time

    #관측기간과 스텝에 따른 관측할 베타 수
    count_step = observation_period//observation_step
    #230, 225, 220 ... 5. 기간별 베타.
    BoB_period = [x*5 for x in reversed(range(1, count_step+1))]
    #460, 455, 450 ... 235. 스텝 베타.
    BoB_time = [x*5+observation_period for x in reversed(range(1, count_step))]

    #기간 베타. 230, 225, 220 ... 5일간 관측 베타
    for period in BoB_period:
      BoB.append( getBeta(ticker, pricedata_kospi, kospi_index, period, observation_time) )

    #스텝 베타 벡터. 230~235, 235~240, 240~245 ... 베타 벡터
    for period in BoB_time:
      BoB.append( getBeta(ticker, pricedata_kospi, kospi_index, observation_step, period) )

    state = ticker+'_'+str(pricedata_kospi.index[observation_time])[:10]
    return state, BoB
  except:
    pass

In [12]:
#Period Yield
def getPY(start, end):
  return (end - start)/start

In [13]:
########################   result 획득   ########################
#######input
#ticker -> 목표 종목 코드(string)
#observation_time -> 관측을 하는 시점(int)
#forward_period -> 수익률 계산 기간(int)

#######output
#앞으로 forward_period 기간이 지난 후
#(개별 기간 수익률 상승) and (벤치마크 수익률 상회)
#True, False (bool)
#################################################################
def getClassified(ticker, observation_time, forward_period=50):
  price_start = pricedata_kospi[ticker].iloc[observation_period]
  price_end = pricedata_kospi[ticker].iloc[observation_period+forward_period]
  market_start = kospi_index['코스피'].iloc[observation_period]
  market_end = kospi_index['코스피'].iloc[observation_period+forward_period]
  return getPY(price_start, price_end) > 0 and getPY(price_start, price_end) > getPY(market_start, market_end)

# 랜덤포레스트 활용


In [14]:
observation_period = 230
observation_step = 5
forward_period = 50

## 230시점(2016-12-08) 학습 후 정확도 확인

In [15]:
period_list = [x*230 for x in range(1, 2)]
print(period_list)

[230]


### 데이터셋 생성

In [16]:
%%time
#230시점 생성
index_list = []
BoB_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    state, getedBoB = getBoB(ticker, period)
    index_list.append(state)
    BoB_list.append(getedBoB)
  print()

230
784/784
CPU times: user 2min 5s, sys: 1.98 s, total: 2min 7s
Wall time: 2min 4s


In [17]:
BagOfBeta_df_230 = pd.DataFrame(BoB_list, index = index_list)

In [18]:
classified_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    classified_list.append(getClassified(ticker, period))
  print()

230
784/784


In [19]:
BagOfBeta_df_230['result'] = classified_list
BagOfBeta_df_230_droped = BagOfBeta_df_230.dropna() 

In [20]:
BagOfBeta_df_230_droped 

0         1         2  ...         89         90  result
A005930_2016-12-08  1.338226  1.338483  1.362913  ...   4.917341   1.980648    True
A000660_2016-12-08  1.254750  1.242087  1.220905  ...   6.100980   1.263442    True
A035420_2016-12-08  0.861434  0.880686  0.942875  ...   5.399600  -0.778535   False
A051910_2016-12-08  1.481199  1.455214  1.423273  ...  -8.399359   2.802454    True
A005380_2016-12-08  0.676756  0.702852  0.702668  ...  -3.422478  -1.238860    True
...                      ...       ...       ...  ...        ...        ...     ...
A002420_2016-12-08  0.729908  0.783592  0.814184  ...  -2.084978  -3.255745    True
A004920_2016-12-08  0.427710  0.419726  0.349129  ...  -3.913508  -3.943363    True
A025890_2016-12-08  1.106322  1.072390  1.109527  ...   7.001526   2.256197   False
A010580_2016-12-08  1.749855  1.757707  1.791231  ...  21.286728 -11.434090    True
A008500_2016-12-08  0.230774  0.232657  0.241159  ...  -0.412540  -1.013272   False

[712 rows x 92 columns]

### 학습

In [21]:
train, test = train_test_split(BagOfBeta_df_230_droped, test_size=0.2, random_state=777)
train_x = train[train.columns[:-1]]
train_y = train[train.columns[-1]]
test_x = test[test.columns[:-1]]
test_y = test[test.columns[-1]]

In [22]:
rfc_model_230 = RandomForestClassifier(n_estimators=100, random_state=777, max_depth = 100, min_samples_split = 0.001)
rfc_model_230.fit(train_x, train_y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=100, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=0.001,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=777,
                       verbose=0, warm_start=False)

In [23]:
pred = rfc_model_230.predict(test_x)

print("Accuracy: %s" % str(rfc_model_230.score(test_x, test_y)))
print("Confusion Matrix")
print(confusion_matrix(pred, test_y, labels=[True, False])) 

Accuracy: 0.6433566433566433
Confusion Matrix
[[54 24]
 [27 38]]


## 230_460시점(2016-12-08, 2017-11-17) 학습 후 정확도 확인

In [50]:
period_list = [x*230 for x in range(1, 3)]
print(period_list)

[230, 460]


### 데이터셋 생성

In [51]:
%%time
#230, 460시점 생성
index_list = []
BoB_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    state, getedBoB = getBoB(ticker, period)
    index_list.append(state)
    BoB_list.append(getedBoB)
  print()

230
784/784
460
784/784
CPU times: user 4min 10s, sys: 3.56 s, total: 4min 14s
Wall time: 4min 9s


In [52]:
BagOfBeta_df_230_460 = pd.DataFrame(BoB_list, index = index_list)

In [53]:
classified_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    classified_list.append(getClassified(ticker, period))
  print()

230
784/784
460
784/784


In [54]:
BagOfBeta_df_230_460['result'] = classified_list
BagOfBeta_df_230_460_droped = BagOfBeta_df_230_460.dropna()

In [55]:
BagOfBeta_df_230_460_droped

0         1         2  ...         89         90  result
A005930_2016-12-08  1.338226  1.338483  1.362913  ...   4.917341   1.980648    True
A000660_2016-12-08  1.254750  1.242087  1.220905  ...   6.100980   1.263442    True
A035420_2016-12-08  0.861434  0.880686  0.942875  ...   5.399600  -0.778535   False
A051910_2016-12-08  1.481199  1.455214  1.423273  ...  -8.399359   2.802454    True
A005380_2016-12-08  0.676756  0.702852  0.702668  ...  -3.422478  -1.238860    True
...                      ...       ...       ...  ...        ...        ...     ...
A002420_2017-11-17  0.317023  0.330622  0.328512  ...  -2.084978  -3.255745    True
A004920_2017-11-17  0.996110  1.018340  1.030405  ...  -3.913508  -3.943363    True
A025890_2017-11-17  0.267079  0.263221  0.254097  ...   7.001526   2.256197   False
A010580_2017-11-17  0.508732  0.557618  0.516569  ...  21.286728 -11.434090    True
A008500_2017-11-17  0.069427  0.073402  0.075852  ...  -0.412540  -1.013272   False

[1439 rows x 92 columns]

### 학습

In [56]:
train, test = train_test_split(BagOfBeta_df_230_460_droped, test_size=0.2, random_state=777)
train_x = train[train.columns[:-1]]
train_y = train[train.columns[-1]]
test_x = test[test.columns[:-1]]
test_y = test[test.columns[-1]]

In [57]:
%%time
rfc_model_230_460 = RandomForestClassifier(n_estimators=1000, random_state=777, max_depth = 500, min_samples_split = 0.001)
rfc_model_230_460.fit(train_x, train_y)

CPU times: user 7.45 s, sys: 31.9 ms, total: 7.49 s
Wall time: 7.49 s


In [58]:
pred = rfc_model_230_460.predict(test_x)

print("Accuracy: %s" % str(rfc_model_230_460.score(test_x, test_y)))
print("Confusion Matrix")
print(confusion_matrix(pred, test_y, labels=[True, False])) 

Accuracy: 0.8298611111111112
Confusion Matrix
[[127  31]
 [ 18 112]]


## 230_460_690_920시점 학습 후 1150시점으로 정확도 검증

In [59]:
period_list = [x*230 for x in range(1, 5)]
print(period_list)

[230, 460, 690, 920]


### 데이터셋 생성

In [60]:
%%time
#230, 460, 690, 920시점 생성
index_list = []
BoB_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    state, getedBoB = getBoB(ticker, period)
    index_list.append(state)
    BoB_list.append(getedBoB)
  print()

230
784/784
460
784/784
690
784/784
920
784/784
CPU times: user 8min 23s, sys: 7.42 s, total: 8min 31s
Wall time: 8min 22s


In [61]:
BagOfBeta_df_230_460_690_920 = pd.DataFrame(BoB_list, index = index_list)

In [62]:
classified_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    classified_list.append(getClassified(ticker, period))
  print()

230
784/784
460
784/784
690
784/784
920
784/784


In [63]:
BagOfBeta_df_230_460_690_920['result'] = classified_list
BagOfBeta_df_230_460_690_920_droped = BagOfBeta_df_230_460_690_920.dropna()

In [64]:
BagOfBeta_df_230_460_690_920_droped

0         1         2  ...         89         90  result
A005930_2016-12-08  1.338226  1.338483  1.362913  ...   4.917341   1.980648    True
A000660_2016-12-08  1.254750  1.242087  1.220905  ...   6.100980   1.263442    True
A035420_2016-12-08  0.861434  0.880686  0.942875  ...   5.399600  -0.778535   False
A051910_2016-12-08  1.481199  1.455214  1.423273  ...  -8.399359   2.802454    True
A005380_2016-12-08  0.676756  0.702852  0.702668  ...  -3.422478  -1.238860    True
...                      ...       ...       ...  ...        ...        ...     ...
A002420_2019-10-07  0.538547  0.609628  0.622467  ...  -2.084978  -3.255745    True
A004920_2019-10-07  0.491324  0.455885  0.426018  ...  -3.913508  -3.943363    True
A025890_2019-10-07  0.658543  0.703296  0.690272  ...   7.001526   2.256197   False
A010580_2019-10-07  0.619922  0.644286  0.634286  ...  21.286728 -11.434090    True
A008500_2019-10-07  0.345035  0.311154  0.292470  ...  -0.412540  -1.013272   False

[2893 rows x 92 columns]

### 학습

In [65]:
train, test = train_test_split(BagOfBeta_df_230_460_690_920_droped, test_size=0.2, random_state=777)
train_x = train[train.columns[:-1]]
train_y = train[train.columns[-1]]
test_x = test[test.columns[:-1]]
test_y = test[test.columns[-1]]

In [66]:
%%time
rfc_model_230_460_690_920 = RandomForestClassifier(n_estimators=1000, random_state=777, max_depth = 500, min_samples_split = 0.001)
rfc_model_230_460_690_920.fit(train_x, train_y)

CPU times: user 15 s, sys: 52.3 ms, total: 15.1 s
Wall time: 15 s


In [67]:
pred = rfc_model_230_460_690_920.predict(test_x)

print("Accuracy: %s" % str(rfc_model_230_460_690_920.score(test_x, test_y)))
print("Confusion Matrix")
print(confusion_matrix(pred, test_y, labels=[True, False]))

Accuracy: 0.92573402417962
Confusion Matrix
[[304  32]
 [ 11 232]]


### 1150시점 으로 검증

#### 1150 데이터셋 생성

In [68]:
%%time
#1150시점 생성
period_list = [1150]
index_list = []
BoB_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    state, getedBoB = getBoB(ticker, period)
    index_list.append(state)
    BoB_list.append(getedBoB)
  print()

1150
784/784
CPU times: user 2min 5s, sys: 1.96 s, total: 2min 7s
Wall time: 2min 5s


In [69]:
BagOfBeta_df_1150 = pd.DataFrame(BoB_list, index = index_list)

In [70]:
classified_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    classified_list.append(getClassified(ticker, period))
  print()

1150
784/784


In [71]:
BagOfBeta_df_1150['result'] = classified_list
BagOfBeta_df_1150_droped = BagOfBeta_df_1150.dropna()

In [72]:
BagOfBeta_df_1150_droped

0         1         2  ...         89         90  result
A005930_2020-09-08  1.012332  1.009569  1.007693  ...   4.917341   1.980648    True
A000660_2020-09-08  1.125174  1.124807  1.118025  ...   6.100980   1.263442    True
A035420_2020-09-08  0.756143  0.758747  0.755372  ...   5.399600  -0.778535   False
A051910_2020-09-08  1.363505  1.366519  1.368219  ...  -8.399359   2.802454    True
A207940_2020-09-08  0.861212  0.862500  0.861083  ...   3.921147   8.577939    True
...                      ...       ...       ...  ...        ...        ...     ...
A002420_2020-09-08  0.442418  0.443538  0.440927  ...  -2.084978  -3.255745    True
A004920_2020-09-08  0.410942  0.408065  0.408501  ...  -3.913508  -3.943363    True
A025890_2020-09-08  0.762727  0.757473  0.758853  ...   7.001526   2.256197   False
A010580_2020-09-08  0.457262  0.459406  0.462919  ...  21.286728 -11.434090    True
A008500_2020-09-08  0.463901  0.464882  0.468846  ...  -0.412540  -1.013272   False

[727 rows x 92 columns]

#### 위에서 학습한 각 모델들로 검증

In [73]:
test_x = BagOfBeta_df_1150_droped[BagOfBeta_df_1150_droped.columns[:-1]]
test_y = BagOfBeta_df_1150_droped[BagOfBeta_df_1150_droped.columns[-1]]

In [75]:
pred = rfc_model_230.predict(test_x)

print("Accuracy: %s" % str(rfc_model_230.score(test_x, test_y)))
print("Confusion Matrix")
print(confusion_matrix(pred, test_y, labels=[True, False]))

Accuracy: 0.7565337001375516
Confusion Matrix
[[279  84]
 [ 93 271]]


In [76]:
pred = rfc_model_230_460.predict(test_x)

print("Accuracy: %s" % str(rfc_model_230_460.score(test_x, test_y)))
print("Confusion Matrix")
print(confusion_matrix(pred, test_y, labels=[True, False])) 

Accuracy: 0.9284731774415406
Confusion Matrix
[[362  42]
 [ 10 313]]


In [77]:
pred = rfc_model_230_460_690_920.predict(test_x)

print("Accuracy: %s" % str(rfc_model_230_460_690_920.score(test_x, test_y)))
print("Confusion Matrix")
print(confusion_matrix(pred, test_y, labels=[True, False]))

Accuracy: 0.9614855570839065
Confusion Matrix
[[368  24]
 [  4 331]]


## 전체 학습(230, 460 690, 920, 1150)후 현 시점(2021-03-29) 데이터로 스크리닝

In [78]:
period_list = [x*230 for x in range(1, 6)]
print(period_list)

[230, 460, 690, 920, 1150]


### 데이터셋 생성

In [79]:
%%time
#230, 460, 690, 920, 1150시점 생성
index_list = []
BoB_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    state, getedBoB = getBoB(ticker, period)
    index_list.append(state)
    BoB_list.append(getedBoB)
  print()

230
784/784
460
784/784
690
784/784
920
784/784
1150
784/784
CPU times: user 10min 28s, sys: 9.38 s, total: 10min 37s
Wall time: 10min 26s


In [80]:
BagOfBeta_df_230_460_690_920_1150 = pd.DataFrame(BoB_list, index = index_list)

In [81]:
classified_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    classified_list.append(getClassified(ticker, period))
  print()

230
784/784
460
784/784
690
784/784
920
784/784
1150
784/784


In [82]:
BagOfBeta_df_230_460_690_920_1150['result'] = classified_list
BagOfBeta_df_230_460_690_920_1150_droped = BagOfBeta_df_230_460_690_920_1150.dropna()

In [83]:
BagOfBeta_df_230_460_690_920_1150_droped

0         1         2  ...         89         90  result
A005930_2016-12-08  1.338226  1.338483  1.362913  ...   4.917341   1.980648    True
A000660_2016-12-08  1.254750  1.242087  1.220905  ...   6.100980   1.263442    True
A035420_2016-12-08  0.861434  0.880686  0.942875  ...   5.399600  -0.778535   False
A051910_2016-12-08  1.481199  1.455214  1.423273  ...  -8.399359   2.802454    True
A005380_2016-12-08  0.676756  0.702852  0.702668  ...  -3.422478  -1.238860    True
...                      ...       ...       ...  ...        ...        ...     ...
A002420_2020-09-08  0.442418  0.443538  0.440927  ...  -2.084978  -3.255745    True
A004920_2020-09-08  0.410942  0.408065  0.408501  ...  -3.913508  -3.943363    True
A025890_2020-09-08  0.762727  0.757473  0.758853  ...   7.001526   2.256197   False
A010580_2020-09-08  0.457262  0.459406  0.462919  ...  21.286728 -11.434090    True
A008500_2020-09-08  0.463901  0.464882  0.468846  ...  -0.412540  -1.013272   False

[3620 rows x 92 columns]

### 학습

In [88]:
train, test = train_test_split(BagOfBeta_df_230_460_690_920_1150_droped, test_size=0.2, random_state=777)

In [89]:
train_x = train[train.columns[:-1]]
train_y = train[train.columns[-1]]

In [90]:
test_x = test[test.columns[:-1]]
test_y = test[test.columns[-1]]

In [91]:
%%time
rfc_model_230_460_690_920_1150 = RandomForestClassifier(n_estimators=1000, random_state=777, max_depth = 500, min_samples_split = 0.001)
rfc_model_230_460_690_920_1150.fit(train_x, train_y)

CPU times: user 18.4 s, sys: 60.8 ms, total: 18.5 s
Wall time: 18.5 s


In [92]:
pred = rfc_model_230_460_690_920_1150.predict(test_x)

print("Accuracy: %s" % str(rfc_model_230_460_690_920_1150.score(test_x, test_y)))
print("Confusion Matrix")
print(confusion_matrix(pred, test_y, labels=[True, False]))

Accuracy: 0.9765193370165746
Confusion Matrix
[[363  10]
 [  7 344]]


### 스크리닝

In [ ]:
# 현 시점 데이터(2021-03-29)로 230_460_690_920_1150 모델로 스크리닝

#### 1284시점(21-03-29) 관측 베타 데이터 생성

In [93]:
%%time
index_list = []
BoB_list = []
#현시점(1284, 21-03-29) 생성
for i, ticker in enumerate(pricedata_kospi.columns):
  print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
  state, getedBoB = getBoB(ticker, 1284)
  index_list.append(state)
  BoB_list.append(getedBoB)
print()

784/784
CPU times: user 2min 6s, sys: 1.75 s, total: 2min 8s
Wall time: 2min 6s


In [94]:
BagOfBeta_df_1284 = pd.DataFrame(BoB_list, index = index_list)
BagOfBeta_df_1284

0         1   ...         89         90
A005930_2021-03-29  1.106133  1.113892  ...   4.917341   1.980648
A000660_2021-03-29  1.185804  1.190289  ...   6.100980   1.263442
A035420_2021-03-29  0.760223  0.756119  ...   5.399600  -0.778535
A051910_2021-03-29  1.338697  1.347034  ...  -8.399359   2.802454
A207940_2021-03-29  0.689753  0.689167  ...   3.921147   8.577939
...                      ...       ...  ...        ...        ...
A002420_2021-03-29  0.205858  0.192678  ...  -2.084978  -3.255745
A004920_2021-03-29  0.519117  0.476764  ...  -3.913508  -3.943363
A025890_2021-03-29  0.587794  0.595959  ...   7.001526   2.256197
A010580_2021-03-29  0.000000  0.000000  ...  21.286728 -11.434090
A008500_2021-03-29 -0.323785 -0.339107  ...  -0.412540  -1.013272

[784 rows x 91 columns]

In [95]:
BagOfBeta_df_1284_droped = BagOfBeta_df_1284.dropna()

In [96]:
BagOfBeta_df_1284_droped

0         1   ...         89         90
A005930_2021-03-29  1.106133  1.113892  ...   4.917341   1.980648
A000660_2021-03-29  1.185804  1.190289  ...   6.100980   1.263442
A035420_2021-03-29  0.760223  0.756119  ...   5.399600  -0.778535
A051910_2021-03-29  1.338697  1.347034  ...  -8.399359   2.802454
A207940_2021-03-29  0.689753  0.689167  ...   3.921147   8.577939
...                      ...       ...  ...        ...        ...
A002420_2021-03-29  0.205858  0.192678  ...  -2.084978  -3.255745
A004920_2021-03-29  0.519117  0.476764  ...  -3.913508  -3.943363
A025890_2021-03-29  0.587794  0.595959  ...   7.001526   2.256197
A010580_2021-03-29  0.000000  0.000000  ...  21.286728 -11.434090
A008500_2021-03-29 -0.323785 -0.339107  ...  -0.412540  -1.013272

[727 rows x 91 columns]

#### 230_460_690_920_1150 모델로 예측

In [97]:
pred = rfc_model_230_460_690_920_1150.predict(BagOfBeta_df_1284_droped)

In [98]:
BagOfBeta_df_1284_droped['pred'] = pred.tolist()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [99]:
BagOfBeta_df_1284_droped

0         1         2  ...         89         90   pred
A005930_2021-03-29  1.106133  1.113892  1.118470  ...   4.917341   1.980648   True
A000660_2021-03-29  1.185804  1.190289  1.188326  ...   6.100980   1.263442   True
A035420_2021-03-29  0.760223  0.756119  0.760356  ...   5.399600  -0.778535  False
A051910_2021-03-29  1.338697  1.347034  1.347610  ...  -8.399359   2.802454   True
A207940_2021-03-29  0.689753  0.689167  0.656946  ...   3.921147   8.577939   True
...                      ...       ...       ...  ...        ...        ...    ...
A002420_2021-03-29  0.205858  0.192678  0.203196  ...  -2.084978  -3.255745   True
A004920_2021-03-29  0.519117  0.476764  0.450303  ...  -3.913508  -3.943363   True
A025890_2021-03-29  0.587794  0.595959  0.615006  ...   7.001526   2.256197  False
A010580_2021-03-29  0.000000  0.000000  0.000000  ...  21.286728 -11.434090   True
A008500_2021-03-29 -0.323785 -0.339107 -0.341056  ...  -0.412540  -1.013272  False

[727 rows x 92 columns]

In [100]:
screened_raw = BagOfBeta_df_1284_droped[BagOfBeta_df_1284_droped['pred']==True].index
screened_raw

Index(['A005930_2021-03-29', 'A000660_2021-03-29', 'A051910_2021-03-29',
       'A207940_2021-03-29', 'A005380_2021-03-29', 'A006400_2021-03-29',
       'A035720_2021-03-29', 'A068270_2021-03-29', 'A066570_2021-03-29',
       'A105560_2021-03-29',
       ...
       'A010420_2021-03-29', 'A011230_2021-03-29', 'A084870_2021-03-29',
       'A001210_2021-03-29', 'A001420_2021-03-29', 'A003280_2021-03-29',
       'A001770_2021-03-29', 'A002420_2021-03-29', 'A004920_2021-03-29',
       'A010580_2021-03-29'],
      dtype='object', length=369)

In [101]:
screened = []
for raw_name in screened_raw:
  screened.append(raw_name[:7])

In [102]:
print(screened)

['A005930', 'A000660', 'A051910', 'A207940', 'A005380', 'A006400', 'A035720', 'A068270', 'A066570', 'A105560', 'A036570', 'A003550', 'A009150', 'A086790', 'A003670', 'A011200', 'A011170', 'A009830', 'A004020', 'A006800', 'A161390', 'A032640', 'A000720', 'A139480', 'A019170', 'A011070', 'A071050', 'A034020', 'A011790', 'A010140', 'A000100', 'A006280', 'A008930', 'A128940', 'A006360', 'A028670', 'A023530', 'A004990', 'A016360', 'A039490', 'A005940', 'A112610', 'A204320', 'A020150', 'A012510', 'A007070', 'A008560', 'A081660', 'A047040', 'A028050', 'A009240', 'A010060', 'A030000', 'A000990', 'A064350', 'A006650', 'A006260', 'A007310', 'A007700', 'A003090', 'A010120', 'A111770', 'A003000', 'A005250', 'A185750', 'A069620', 'A031430', 'A004000', 'A181710', 'A139130', 'A032350', 'A161890', 'A013890', 'A192820', 'A192080', 'A023590', 'A214320', 'A009420', 'A042700', 'A001230', 'A002840', 'A003850', 'A005850', 'A241590', 'A005440', 'A079160', 'A071840', 'A057050', 'A006040', 'A039130', 'A005690'

# 스크린된 종목

In [104]:
len(screened)

369

In [103]:
print(kospi_list[screened].iloc[0].to_list())

['삼성전자', 'SK하이닉스', 'LG화학', '삼성바이오로직스', '현대차', '삼성SDI', '카카오', '셀트리온', 'LG전자', 'KB금융', '엔씨소프트', 'LG', '삼성전기', '하나금융지주', '포스코케미칼', 'HMM', '롯데케미칼', '한화솔루션', '현대제철', '미래에셋대우', '한국타이어앤테크놀로지', 'LG유플러스', '현대건설', '이마트', '신풍제약', 'LG이노텍', '한국금융지주', '두산중공업', 'SKC', '삼성중공업', '유한양행', '녹십자', '한미사이언스', '한미약품', 'GS건설', '팬오션', '롯데쇼핑', '롯데지주', '삼성증권', '키움증권', 'NH투자증권', '씨에스윈드', '만도', '일진머티리얼즈', '더존비즈온', 'GS리테일', '메리츠증권', '휠라홀딩스', '대우건설', '삼성엔지니어링', '한샘', 'OCI', '제일기획', 'DB하이텍', '현대로템', '대한유화', 'LS', '오뚜기', 'F&F', '대웅', 'LS ELECTRIC', '영원무역', '부광약품', '녹십자홀딩스', '종근당', '대웅제약', '신세계인터내셔날', '롯데정밀화학', 'NHN', 'DGB금융지주', '롯데관광개발', '한국콜마', '지누스', '코스맥스', '더블유게임즈', '다우기술', '이노션', '한올바이오파마', '한미반도체', '동국제강', '미원상사', '보령제약', '에스엘', '화승엔터프라이즈', '현대그린푸드', 'CJ CGV', '롯데하이마트', '현대홈쇼핑', '동원산업', '하나투어', '파미셀', '제주항공', '대한해운', '쿠쿠홀딩스', '제이콘텐트리', '한세실업', '유나이티드제약', '한전기술', '대신증권', '락앤락', '미래에셋생명', '동원F&B', 'LG하우시스', '동아에스티', '삼화콘덴서', '삼양식품', '유안타증권', '일양약품', 'NICE', '풀무원', '한화투자증권', '신성이엔지', 'JW중외제약', 'SPC삼립', 'BGF', '잇츠한불