# 환경설정

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
import matplotlib.pyplot as plt

In [4]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

In [5]:
kospi_index = pd.read_excel('https://github.com/SNMHZ/DART_8TH/raw/master/mock_investing/data/kospi_index.xlsx', index_col=0)

In [6]:
kospi_list = pd.read_excel('https://github.com/SNMHZ/DART_8TH/raw/master/mock_investing/data/kospi_list.xlsx', index_col=0)

In [7]:
%%time
pricedata = pd.read_excel('https://github.com/SNMHZ/DART_8TH/raw/master/mock_investing/data/revised_price.xlsx', index_col=0)

CPU times: user 28.8 s, sys: 643 ms, total: 29.5 s
Wall time: 29.8 s


In [8]:
ticker_name = pd.read_excel('https://github.com/SNMHZ/DART_8TH/raw/master/mock_investing/data/ticker_name.xlsx', index_col=0)

In [9]:
pricedata_kospi = pricedata[kospi_list.columns]

# 함수

In [10]:
#########################   베타 획득   #########################
#######input
#ticker -> 목표 종목 코드(string)
#priceData -> 가격 정보 데이터프레임. 시계열
#market -> 시장 지수 데이터프레임. 시계열
#period -> 관측 목표 기간
#end -> 관측 마지막 시점
#show_plot -> 베타 그래프 출력 유무. True시 출력.

#######output
#베타(float)
#################################################################
def getBeta(ticker, priceData, market, period, end=0, show_plot=False):
  price_change = priceData[ticker].pct_change()[1:]
  market_change = market[market.columns[0]].pct_change()[1:]
  
  start = end - period

  price_change_sliced = price_change.iloc[start:end]
  market_change_sliced = market_change.iloc[start:end]

  if show_plot:
    model = LinearRegression(normalize=True)
    model.fit(pd.DataFrame(market_change_sliced),pd.DataFrame(price_change_sliced))

    plt.figure(figsize=(7, 7))
    plt.grid(True)
    plt.scatter(market_change_sliced, price_change_sliced, color='black', alpha=0.5)
    aran = np.arange(min(market_change_sliced) ,max(market_change_sliced) , 0.001)
    plt.plot(aran, model.predict(aran.reshape(-1, 1)), color='blue')
    
    plt.show()

  return (np.cov(price_change_sliced, market_change_sliced)/np.var(market_change_sliced))[0,1]

In [11]:
######################   Bag of Beta 획득   #####################
#######input
#ticker -> 목표 종목 코드(string)
#observation_time -> 관측을 하는 시점(int)
#observation_period -> 관측할 기간(int)
#observation_step -> 관측 step(int)

#######output
#state -> '종목코드_관측시점'. ex) 'A005930_2016-12-08'(string)
#BoB -> 기간 베타 리스트. [230베타, 225베타 220베타, ... , 10~15베타, 5~10베타, 0~5베타](list)
#################################################################
def getBoB(ticker, observation_time, observation_period=230, observation_step=5):
  try:
    BoB = []
    current_period = observation_time

    #관측기간과 스텝에 따른 관측할 베타 수
    count_step = observation_period//observation_step
    #230, 225, 220 ... 5. 기간별 베타.
    BoB_period = [x*5 for x in reversed(range(1, count_step+1))]
    #460, 455, 450 ... 235. 스텝 베타.
    BoB_time = [x*5+observation_period for x in reversed(range(1, count_step))]

    #기간 베타. 230, 225, 220 ... 5일간 관측 베타
    for period in BoB_period:
      BoB.append( getBeta(ticker, pricedata_kospi, kospi_index, period, observation_time) )

    #스텝 베타 벡터. 230~235, 235~240, 240~245 ... 베타 벡터
    for period in BoB_time:
      BoB.append( getBeta(ticker, pricedata_kospi, kospi_index, observation_step, period) )

    state = ticker+'_'+str(pricedata_kospi.index[observation_time])[:10]
    return state, BoB
  except:
    pass

In [12]:
#Period Yield
def getPY(start, end):
  return (end - start)/start

In [13]:
########################   result 획득   ########################
#######input
#ticker -> 목표 종목 코드(string)
#observation_time -> 관측을 하는 시점(int)
#forward_period -> 수익률 계산 기간(int)

#######output
#앞으로 forward_period 기간이 지난 후
#(개별 기간 수익률 상승) and (벤치마크 수익률 상회)
#True, False (bool)
#################################################################
def getClassified(ticker, observation_time, forward_period=50):
  price_start = pricedata_kospi[ticker].iloc[observation_time]
  price_end = pricedata_kospi[ticker].iloc[observation_time+forward_period]
  market_start = kospi_index['코스피'].iloc[observation_time]
  market_end = kospi_index['코스피'].iloc[observation_time+forward_period]
  return getPY(price_start, price_end) > 0 and getPY(price_start, price_end) > getPY(market_start, market_end)

# 랜덤포레스트 활용


In [16]:
observation_period = 230
observation_step = 5
forward_period = 50

## 230시점(2016-12-08) 학습 후 정확도 확인

In [17]:
period_list = [x*230 for x in range(1, 2)]
print(period_list)

[230]


### 데이터셋 생성

In [18]:
%%time
#230시점 생성
index_list = []
BoB_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    state, getedBoB = getBoB(ticker, period)
    index_list.append(state)
    BoB_list.append(getedBoB)
  print()

230
784/784
CPU times: user 2min 14s, sys: 1.96 s, total: 2min 16s
Wall time: 2min 13s


In [19]:
BagOfBeta_df_230 = pd.DataFrame(BoB_list, index = index_list)

In [20]:
classified_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    classified_list.append(getClassified(ticker, period))
  print()

230
784/784


In [21]:
BagOfBeta_df_230['result'] = classified_list
BagOfBeta_df_230_droped = BagOfBeta_df_230.dropna() 

In [22]:
BagOfBeta_df_230_droped 

0         1         2  ...         89         90  result
A005930_2016-12-08  1.338226  1.338483  1.362913  ...   4.917341   1.980648    True
A000660_2016-12-08  1.254750  1.242087  1.220905  ...   6.100980   1.263442    True
A035420_2016-12-08  0.861434  0.880686  0.942875  ...   5.399600  -0.778535   False
A051910_2016-12-08  1.481199  1.455214  1.423273  ...  -8.399359   2.802454    True
A005380_2016-12-08  0.676756  0.702852  0.702668  ...  -3.422478  -1.238860    True
...                      ...       ...       ...  ...        ...        ...     ...
A002420_2016-12-08  0.729908  0.783592  0.814184  ...  -2.084978  -3.255745    True
A004920_2016-12-08  0.427710  0.419726  0.349129  ...  -3.913508  -3.943363    True
A025890_2016-12-08  1.106322  1.072390  1.109527  ...   7.001526   2.256197   False
A010580_2016-12-08  1.749855  1.757707  1.791231  ...  21.286728 -11.434090    True
A008500_2016-12-08  0.230774  0.232657  0.241159  ...  -0.412540  -1.013272   False

[712 rows x 92 columns]

### 학습

In [23]:
train, test = train_test_split(BagOfBeta_df_230_droped, test_size=0.2, random_state=777)
train_x = train[train.columns[:-1]]
train_y = train[train.columns[-1]]
test_x = test[test.columns[:-1]]
test_y = test[test.columns[-1]]

In [24]:
rfc_model_230 = RandomForestClassifier(n_estimators=100, random_state=777, max_depth = 100, min_samples_split = 0.001)
rfc_model_230.fit(train_x, train_y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=100, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=0.001,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=777,
                       verbose=0, warm_start=False)

In [25]:
pred = rfc_model_230.predict(test_x)

print("Accuracy: %s" % str(rfc_model_230.score(test_x, test_y)))
print("Confusion Matrix")
print(confusion_matrix(pred, test_y, labels=[True, False])) 

Accuracy: 0.6433566433566433
Confusion Matrix
[[54 24]
 [27 38]]


## 230_460시점(2016-12-08, 2017-11-17) 학습 후 정확도 확인

In [26]:
period_list = [x*230 for x in range(1, 3)]
print(period_list)

[230, 460]


### 데이터셋 생성

In [27]:
%%time
#230, 460시점 생성
index_list = []
BoB_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    state, getedBoB = getBoB(ticker, period)
    index_list.append(state)
    BoB_list.append(getedBoB)
  print()

230
784/784
460
784/784
CPU times: user 4min 30s, sys: 4.61 s, total: 4min 35s
Wall time: 4min 29s


In [28]:
BagOfBeta_df_230_460 = pd.DataFrame(BoB_list, index = index_list)

In [29]:
classified_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    classified_list.append(getClassified(ticker, period))
  print()

230
784/784
460
784/784


In [30]:
BagOfBeta_df_230_460['result'] = classified_list
BagOfBeta_df_230_460_droped = BagOfBeta_df_230_460.dropna()

In [31]:
BagOfBeta_df_230_460_droped

0         1         2  ...         89         90  result
A005930_2016-12-08  1.338226  1.338483  1.362913  ...   4.917341   1.980648    True
A000660_2016-12-08  1.254750  1.242087  1.220905  ...   6.100980   1.263442    True
A035420_2016-12-08  0.861434  0.880686  0.942875  ...   5.399600  -0.778535   False
A051910_2016-12-08  1.481199  1.455214  1.423273  ...  -8.399359   2.802454    True
A005380_2016-12-08  0.676756  0.702852  0.702668  ...  -3.422478  -1.238860    True
...                      ...       ...       ...  ...        ...        ...     ...
A002420_2017-11-17  0.317023  0.330622  0.328512  ...  -2.084978  -3.255745    True
A004920_2017-11-17  0.996110  1.018340  1.030405  ...  -3.913508  -3.943363    True
A025890_2017-11-17  0.267079  0.263221  0.254097  ...   7.001526   2.256197    True
A010580_2017-11-17  0.508732  0.557618  0.516569  ...  21.286728 -11.434090   False
A008500_2017-11-17  0.069427  0.073402  0.075852  ...  -0.412540  -1.013272   False

[1439 rows x 92 columns]

### 학습

In [32]:
train, test = train_test_split(BagOfBeta_df_230_460_droped, test_size=0.2, random_state=777)
train_x = train[train.columns[:-1]]
train_y = train[train.columns[-1]]
test_x = test[test.columns[:-1]]
test_y = test[test.columns[-1]]

In [33]:
%%time
rfc_model_230_460 = RandomForestClassifier(n_estimators=1000, random_state=777, max_depth = 500, min_samples_split = 0.001)
rfc_model_230_460.fit(train_x, train_y)

CPU times: user 8.15 s, sys: 39.3 ms, total: 8.19 s
Wall time: 8.16 s


In [34]:
pred = rfc_model_230_460.predict(test_x)

print("Accuracy: %s" % str(rfc_model_230_460.score(test_x, test_y)))
print("Confusion Matrix")
print(confusion_matrix(pred, test_y, labels=[True, False])) 

Accuracy: 0.6006944444444444
Confusion Matrix
[[117  70]
 [ 45  56]]


## 230_460_690_920시점 학습 후 1150시점으로 정확도 검증

In [35]:
period_list = [x*230 for x in range(1, 5)]
print(period_list)

[230, 460, 690, 920]


### 데이터셋 생성

In [36]:
%%time
#230, 460, 690, 920시점 생성
index_list = []
BoB_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    state, getedBoB = getBoB(ticker, period)
    index_list.append(state)
    BoB_list.append(getedBoB)
  print()

230
784/784
460
784/784
690
784/784
920
784/784
CPU times: user 8min 59s, sys: 8.88 s, total: 9min 8s
Wall time: 8min 56s


In [37]:
BagOfBeta_df_230_460_690_920 = pd.DataFrame(BoB_list, index = index_list)

In [38]:
classified_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    classified_list.append(getClassified(ticker, period))
  print()

230
784/784
460
784/784
690
784/784
920
784/784


In [39]:
BagOfBeta_df_230_460_690_920['result'] = classified_list
BagOfBeta_df_230_460_690_920_droped = BagOfBeta_df_230_460_690_920.dropna()

In [40]:
BagOfBeta_df_230_460_690_920_droped

0         1         2  ...         89         90  result
A005930_2016-12-08  1.338226  1.338483  1.362913  ...   4.917341   1.980648    True
A000660_2016-12-08  1.254750  1.242087  1.220905  ...   6.100980   1.263442    True
A035420_2016-12-08  0.861434  0.880686  0.942875  ...   5.399600  -0.778535   False
A051910_2016-12-08  1.481199  1.455214  1.423273  ...  -8.399359   2.802454    True
A005380_2016-12-08  0.676756  0.702852  0.702668  ...  -3.422478  -1.238860    True
...                      ...       ...       ...  ...        ...        ...     ...
A002420_2019-10-07  0.538547  0.609628  0.622467  ...  -2.084978  -3.255745   False
A004920_2019-10-07  0.491324  0.455885  0.426018  ...  -3.913508  -3.943363   False
A025890_2019-10-07  0.658543  0.703296  0.690272  ...   7.001526   2.256197    True
A010580_2019-10-07  0.619922  0.644286  0.634286  ...  21.286728 -11.434090   False
A008500_2019-10-07  0.345035  0.311154  0.292470  ...  -0.412540  -1.013272   False

[2893 rows x 92 columns]

### 학습

In [41]:
train, test = train_test_split(BagOfBeta_df_230_460_690_920_droped, test_size=0.2, random_state=777)
train_x = train[train.columns[:-1]]
train_y = train[train.columns[-1]]
test_x = test[test.columns[:-1]]
test_y = test[test.columns[-1]]

In [42]:
%%time
rfc_model_230_460_690_920 = RandomForestClassifier(n_estimators=1000, random_state=777, max_depth = 500, min_samples_split = 0.001)
rfc_model_230_460_690_920.fit(train_x, train_y)

CPU times: user 17.5 s, sys: 137 ms, total: 17.6 s
Wall time: 17.5 s


In [43]:
pred = rfc_model_230_460_690_920.predict(test_x)

print("Accuracy: %s" % str(rfc_model_230_460_690_920.score(test_x, test_y)))
print("Confusion Matrix")
print(confusion_matrix(pred, test_y, labels=[True, False]))

Accuracy: 0.5785837651122625
Confusion Matrix
[[201 154]
 [ 90 134]]


### 1150시점 으로 검증

#### 1150 데이터셋 생성

In [44]:
%%time
#1150시점 생성
period_list = [1150]
index_list = []
BoB_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    state, getedBoB = getBoB(ticker, period)
    index_list.append(state)
    BoB_list.append(getedBoB)
  print()

1150
784/784
CPU times: user 2min 13s, sys: 2.15 s, total: 2min 15s
Wall time: 2min 12s


In [45]:
BagOfBeta_df_1150 = pd.DataFrame(BoB_list, index = index_list)

In [46]:
classified_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    classified_list.append(getClassified(ticker, period))
  print()

1150
784/784


In [47]:
BagOfBeta_df_1150['result'] = classified_list
BagOfBeta_df_1150_droped = BagOfBeta_df_1150.dropna()

In [48]:
BagOfBeta_df_1150_droped

0         1         2  ...         89         90  result
A005930_2020-09-08  1.012332  1.009569  1.007693  ...   4.917341   1.980648    True
A000660_2020-09-08  1.125174  1.124807  1.118025  ...   6.100980   1.263442    True
A035420_2020-09-08  0.756143  0.758747  0.755372  ...   5.399600  -0.778535   False
A051910_2020-09-08  1.363505  1.366519  1.368219  ...  -8.399359   2.802454   False
A207940_2020-09-08  0.861212  0.862500  0.861083  ...   3.921147   8.577939   False
...                      ...       ...       ...  ...        ...        ...     ...
A002420_2020-09-08  0.442418  0.443538  0.440927  ...  -2.084978  -3.255745   False
A004920_2020-09-08  0.410942  0.408065  0.408501  ...  -3.913508  -3.943363   False
A025890_2020-09-08  0.762727  0.757473  0.758853  ...   7.001526   2.256197    True
A010580_2020-09-08  0.457262  0.459406  0.462919  ...  21.286728 -11.434090   False
A008500_2020-09-08  0.463901  0.464882  0.468846  ...  -0.412540  -1.013272    True

[727 rows x 92 columns]

#### 위에서 학습한 각 모델들로 검증

In [49]:
test_x = BagOfBeta_df_1150_droped[BagOfBeta_df_1150_droped.columns[:-1]]
test_y = BagOfBeta_df_1150_droped[BagOfBeta_df_1150_droped.columns[-1]]

In [50]:
pred = rfc_model_230.predict(test_x)

print("Accuracy: %s" % str(rfc_model_230.score(test_x, test_y)))
print("Confusion Matrix")
print(confusion_matrix(pred, test_y, labels=[True, False]))

Accuracy: 0.5281980742778541
Confusion Matrix
[[157 206]
 [137 227]]


In [51]:
pred = rfc_model_230_460.predict(test_x)

print("Accuracy: %s" % str(rfc_model_230_460.score(test_x, test_y)))
print("Confusion Matrix")
print(confusion_matrix(pred, test_y, labels=[True, False])) 

Accuracy: 0.4924346629986245
Confusion Matrix
[[204 279]
 [ 90 154]]


In [52]:
pred = rfc_model_230_460_690_920.predict(test_x)

print("Accuracy: %s" % str(rfc_model_230_460_690_920.score(test_x, test_y)))
print("Confusion Matrix")
print(confusion_matrix(pred, test_y, labels=[True, False]))

Accuracy: 0.47042640990371387
Confusion Matrix
[[181 272]
 [113 161]]


## 전체 학습(230, 460 690, 920, 1150)후 현 시점(2021-03-29) 데이터로 스크리닝

In [53]:
period_list = [x*230 for x in range(1, 6)]
print(period_list)

[230, 460, 690, 920, 1150]


### 데이터셋 생성

In [54]:
%%time
#230, 460, 690, 920, 1150시점 생성
index_list = []
BoB_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    state, getedBoB = getBoB(ticker, period)
    index_list.append(state)
    BoB_list.append(getedBoB)
  print()

230
784/784
460
784/784
690
784/784
920
784/784
1150
784/784
CPU times: user 11min 10s, sys: 11.1 s, total: 11min 21s
Wall time: 11min 6s


In [55]:
BagOfBeta_df_230_460_690_920_1150 = pd.DataFrame(BoB_list, index = index_list)

In [56]:
classified_list = []
for period in period_list:
  print(period)
  for i, ticker in enumerate(pricedata_kospi.columns):
    print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
    classified_list.append(getClassified(ticker, period))
  print()

230
784/784
460
784/784
690
784/784
920
784/784
1150
784/784


In [57]:
BagOfBeta_df_230_460_690_920_1150['result'] = classified_list
BagOfBeta_df_230_460_690_920_1150_droped = BagOfBeta_df_230_460_690_920_1150.dropna()

In [58]:
BagOfBeta_df_230_460_690_920_1150_droped

0         1         2  ...         89         90  result
A005930_2016-12-08  1.338226  1.338483  1.362913  ...   4.917341   1.980648    True
A000660_2016-12-08  1.254750  1.242087  1.220905  ...   6.100980   1.263442    True
A035420_2016-12-08  0.861434  0.880686  0.942875  ...   5.399600  -0.778535   False
A051910_2016-12-08  1.481199  1.455214  1.423273  ...  -8.399359   2.802454    True
A005380_2016-12-08  0.676756  0.702852  0.702668  ...  -3.422478  -1.238860    True
...                      ...       ...       ...  ...        ...        ...     ...
A002420_2020-09-08  0.442418  0.443538  0.440927  ...  -2.084978  -3.255745   False
A004920_2020-09-08  0.410942  0.408065  0.408501  ...  -3.913508  -3.943363   False
A025890_2020-09-08  0.762727  0.757473  0.758853  ...   7.001526   2.256197    True
A010580_2020-09-08  0.457262  0.459406  0.462919  ...  21.286728 -11.434090   False
A008500_2020-09-08  0.463901  0.464882  0.468846  ...  -0.412540  -1.013272    True

[3620 rows x 92 columns]

### 학습

In [59]:
train, test = train_test_split(BagOfBeta_df_230_460_690_920_1150_droped, test_size=0.2, random_state=777)

In [60]:
train_x = train[train.columns[:-1]]
train_y = train[train.columns[-1]]

In [61]:
test_x = test[test.columns[:-1]]
test_y = test[test.columns[-1]]

In [62]:
%%time
rfc_model_230_460_690_920_1150 = RandomForestClassifier(n_estimators=1000, random_state=777, max_depth = 500, min_samples_split = 0.001)
rfc_model_230_460_690_920_1150.fit(train_x, train_y)

CPU times: user 22.7 s, sys: 186 ms, total: 22.8 s
Wall time: 22.7 s


In [63]:
pred = rfc_model_230_460_690_920_1150.predict(test_x)

print("Accuracy: %s" % str(rfc_model_230_460_690_920_1150.score(test_x, test_y)))
print("Confusion Matrix")
print(confusion_matrix(pred, test_y, labels=[True, False]))

Accuracy: 0.5953038674033149
Confusion Matrix
[[203 131]
 [162 228]]


### 스크리닝

In [64]:
# 현 시점 데이터(2021-03-29)로 230_460_690_920_1150 모델로 스크리닝

#### 1284시점(21-03-29) 관측 베타 데이터 생성

In [65]:
%%time
index_list = []
BoB_list = []
#현시점(1284, 21-03-29) 생성
for i, ticker in enumerate(pricedata_kospi.columns):
  print('\r%d/%d'%(i+1, len(pricedata_kospi.columns)), end='')
  state, getedBoB = getBoB(ticker, 1284)
  index_list.append(state)
  BoB_list.append(getedBoB)
print()

784/784
CPU times: user 2min 12s, sys: 2.06 s, total: 2min 14s
Wall time: 2min 11s


In [66]:
BagOfBeta_df_1284 = pd.DataFrame(BoB_list, index = index_list)
BagOfBeta_df_1284

0         1   ...         89         90
A005930_2021-03-29  1.106133  1.113892  ...   4.917341   1.980648
A000660_2021-03-29  1.185804  1.190289  ...   6.100980   1.263442
A035420_2021-03-29  0.760223  0.756119  ...   5.399600  -0.778535
A051910_2021-03-29  1.338697  1.347034  ...  -8.399359   2.802454
A207940_2021-03-29  0.689753  0.689167  ...   3.921147   8.577939
...                      ...       ...  ...        ...        ...
A002420_2021-03-29  0.205858  0.192678  ...  -2.084978  -3.255745
A004920_2021-03-29  0.519117  0.476764  ...  -3.913508  -3.943363
A025890_2021-03-29  0.587794  0.595959  ...   7.001526   2.256197
A010580_2021-03-29  0.000000  0.000000  ...  21.286728 -11.434090
A008500_2021-03-29 -0.323785 -0.339107  ...  -0.412540  -1.013272

[784 rows x 91 columns]

In [67]:
BagOfBeta_df_1284_droped = BagOfBeta_df_1284.dropna()

In [68]:
BagOfBeta_df_1284_droped

0         1   ...         89         90
A005930_2021-03-29  1.106133  1.113892  ...   4.917341   1.980648
A000660_2021-03-29  1.185804  1.190289  ...   6.100980   1.263442
A035420_2021-03-29  0.760223  0.756119  ...   5.399600  -0.778535
A051910_2021-03-29  1.338697  1.347034  ...  -8.399359   2.802454
A207940_2021-03-29  0.689753  0.689167  ...   3.921147   8.577939
...                      ...       ...  ...        ...        ...
A002420_2021-03-29  0.205858  0.192678  ...  -2.084978  -3.255745
A004920_2021-03-29  0.519117  0.476764  ...  -3.913508  -3.943363
A025890_2021-03-29  0.587794  0.595959  ...   7.001526   2.256197
A010580_2021-03-29  0.000000  0.000000  ...  21.286728 -11.434090
A008500_2021-03-29 -0.323785 -0.339107  ...  -0.412540  -1.013272

[727 rows x 91 columns]

#### 230_460_690_920_1150 모델로 예측

In [69]:
pred = rfc_model_230_460_690_920_1150.predict(BagOfBeta_df_1284_droped)

In [70]:
BagOfBeta_df_1284_droped['pred'] = pred.tolist()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [71]:
BagOfBeta_df_1284_droped

0         1         2  ...         89         90   pred
A005930_2021-03-29  1.106133  1.113892  1.118470  ...   4.917341   1.980648   True
A000660_2021-03-29  1.185804  1.190289  1.188326  ...   6.100980   1.263442   True
A035420_2021-03-29  0.760223  0.756119  0.760356  ...   5.399600  -0.778535   True
A051910_2021-03-29  1.338697  1.347034  1.347610  ...  -8.399359   2.802454   True
A207940_2021-03-29  0.689753  0.689167  0.656946  ...   3.921147   8.577939   True
...                      ...       ...       ...  ...        ...        ...    ...
A002420_2021-03-29  0.205858  0.192678  0.203196  ...  -2.084978  -3.255745  False
A004920_2021-03-29  0.519117  0.476764  0.450303  ...  -3.913508  -3.943363  False
A025890_2021-03-29  0.587794  0.595959  0.615006  ...   7.001526   2.256197  False
A010580_2021-03-29  0.000000  0.000000  0.000000  ...  21.286728 -11.434090  False
A008500_2021-03-29 -0.323785 -0.339107 -0.341056  ...  -0.412540  -1.013272  False

[727 rows x 92 columns]

In [72]:
screened_raw = BagOfBeta_df_1284_droped[BagOfBeta_df_1284_droped['pred']==True].index
screened_raw

Index(['A005930_2021-03-29', 'A000660_2021-03-29', 'A035420_2021-03-29',
       'A051910_2021-03-29', 'A207940_2021-03-29', 'A006400_2021-03-29',
       'A035720_2021-03-29', 'A068270_2021-03-29', 'A005490_2021-03-29',
       'A066570_2021-03-29',
       ...
       'A001620_2021-03-29', 'A071090_2021-03-29', 'A044380_2021-03-29',
       'A018500_2021-03-29', 'A072130_2021-03-29', 'A003680_2021-03-29',
       'A014910_2021-03-29', 'A010420_2021-03-29', 'A005030_2021-03-29',
       'A015260_2021-03-29'],
      dtype='object', length=267)

In [73]:
screened = []
for raw_name in screened_raw:
  screened.append(raw_name[:7])

In [74]:
print(screened)

['A005930', 'A000660', 'A035420', 'A051910', 'A207940', 'A006400', 'A035720', 'A068270', 'A005490', 'A066570', 'A028260', 'A017670', 'A036570', 'A034730', 'A003550', 'A009150', 'A011170', 'A018880', 'A003490', 'A009540', 'A010950', 'A034220', 'A086280', 'A011780', 'A004020', 'A006800', 'A161390', 'A032640', 'A139480', 'A019170', 'A071050', 'A011790', 'A010140', 'A006280', 'A241560', 'A008930', 'A180640', 'A003410', 'A006360', 'A078930', 'A023530', 'A016360', 'A039490', 'A005940', 'A112610', 'A020150', 'A042660', 'A012510', 'A004170', 'A014680', 'A047040', 'A028050', 'A009240', 'A010620', 'A047050', 'A000880', 'A042670', 'A006650', 'A006260', 'A011210', 'A002380', 'A007700', 'A017800', 'A111770', 'A000240', 'A120110', 'A003000', 'A005250', 'A185750', 'A000210', 'A051600', 'A032350', 'A016380', 'A013890', 'A023590', 'A042700', 'A001230', 'A020560', 'A003850', 'A000670', 'A069260', 'A018670', 'A071840', 'A001440', 'A039130', 'A089590', 'A005880', 'A103140', 'A036420', 'A033270', 'A003540'

# 스크린된 종목

In [75]:
len(screened)

267

In [76]:
print(kospi_list[screened].iloc[0].to_list())

['삼성전자', 'SK하이닉스', 'NAVER', 'LG화학', '삼성바이오로직스', '삼성SDI', '카카오', '셀트리온', 'POSCO', 'LG전자', '삼성물산', 'SK텔레콤', '엔씨소프트', 'SK', 'LG', '삼성전기', '롯데케미칼', '한온시스템', '대한항공', '한국조선해양', 'S-Oil', 'LG디스플레이', '현대글로비스', '금호석유', '현대제철', '미래에셋대우', '한국타이어앤테크놀로지', 'LG유플러스', '이마트', '신풍제약', '한국금융지주', 'SKC', '삼성중공업', '녹십자', '두산밥캣', '한미사이언스', '한진칼', '쌍용양회', 'GS건설', 'GS', '롯데쇼핑', '삼성증권', '키움증권', 'NH투자증권', '씨에스윈드', '일진머티리얼즈', '대우조선해양', '더존비즈온', '신세계', '한솔케미칼', '대우건설', '삼성엔지니어링', '한샘', '현대미포조선', '포스코인터내셔널', '한화', '두산인프라코어', '대한유화', 'LS', '현대위아', 'KCC', 'F&F', '현대엘리베이', '영원무역', '한국앤컴퍼니', '코오롱인더', '부광약품', '녹십자홀딩스', '종근당', 'DL', '한전KPS', '롯데관광개발', 'KG동부제철', '지누스', '다우기술', '한미반도체', '동국제강', '아시아나항공', '보령제약', '영풍', '휴켐스', 'SK가스', '롯데하이마트', '대한전선', '하나투어', '제주항공', '대한해운', '풍산', '제이콘텐트리', '유나이티드제약', '대신증권', '한국단자', 'SK디앤디', '한일현대시멘트', '동아쏘시오홀딩스', '유안타증권', '일양약품', '한화투자증권', '신성이엔지', '세아베스틸', 'SPC삼립', 'BGF', '한진중공업', '잇츠한불', '빙그레', '우리종금', '한화손해보험', '진흥기업', '한국토지신탁', '한국카본', '진원생명과학', '해성디에스', '코오롱글로벌', '필룩스', '에이프로젠제약', '삼성